# Generated by Django 5.2.5 on 2025-08-07 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='relatorios/')),
            ],
        ),
        migrations.CreateModel(
            name='DestinatarioEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('ready_line', models.CharField(max_length=16)),
                ('vip_line', models.CharField(max_length=16)),
                ('overflow_kiosk', models.CharField(max_length=16)),
                ('overflow_2', models.CharField(max_length=16)),
                ('black_top', models.CharField(max_length=16)),
                ('return_line', models.CharField(max_length=16)),
                ('mecanico', models.CharField(max_length=16)),
                ('gas_run', models.CharField(max_length=16)),
                ('total_cleaned', models.PositiveIntegerField()),
                ('forecasted_drops', models.PositiveIntegerField()),
                ('status_envio', models.CharField(choices=[('enviado', 'Enviado'), ('nao_enviado', 'Não enviado')], default='nao_enviado', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('imagens', models.ManyToManyField(blank=True, to='core.relatorioimagem')),
            ],
        ),
        migrations.CreateModel(
            name='UserSMTPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_email', models.EmailField(max_length=254)),
                ('smtp_password', models.CharField(max_length=128)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=128)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
