# Generated by Django 5.2.5 on 2025-08-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmtpconfig',
            name='smtp_host',
            field=models.CharField(default='smtp.office365.com', max_length=128),
        ),
    ]
